### ISSUE TITLE
Subtitle Correction for IRM-4-DDOS

### ISSUE THREAD

**Issue by cY-BeR-PaN-Da** [certsocietegenerale/IRM#1]
Firstly, I would like to express my gratitude for sharing this.
Secondly, In the IRM-4-DDOS, subtitle states: "Live Analysis on a suspicious Windows system", which doesn't seem to be right.

**Comment by certsocietegenerale** [comment]
Thank you @cY-BeR-PaN-Da , the IRM-4 subtitle has been corrected.
