### ISSUE TITLE
IRM-1-WormInfection.pdf Error

### ISSUE THREAD

**Issue by trickstersec** [certsocietegenerale/IRM#9]
In the "Preparation" step objective section it should say: 
"OBJECTIVE: ESTABLISH CONTACTS, DEFINE PROCEDURES, GATHER INFORMATION TO SAVE TIME DURING AN INCIDENT."

But it says:
"OBJECTIVE: DETECT THE INCIDENT, DETERMINE ITS SCOPE, AND INVOLVE THE APPROPRIATE PARTIES."

**Comment by ztormhouse** [comment]
Thank you @trickstersec, step objective for IRM-1 has been fixed.
